name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      
      - name: Push to hub
        run: |
          git config --global user.email "bot@kryv.network"
          git config --global user.name "KRYV Bot"
          # 👇 Yahan Maine Tera Username aur Space DIRECT likh diya hai. 
          # Sirf Token secret se aayega. 100% chalega.
          git remote add space https://RajatDatta5315:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/RajatDatta5315/nehira-brain
          git push --force space main

